# Plugins
gems:

safe: false

# Build Settings
markdown: kramdown
permalink: pretty

# Site settings
title: Queer Festival of Colours
email: "addmail@mail.com"
description: Queer Festival of Colours at Cambridge,UK.
baseurl: "/" # the subpath of your site, e.g. /blog/
permalink: "/:title"
keywords: Queer, Festival, Cambridge
author: q+
url: "https://cihernand.github.io/queerfest" # the base hostname & protocol for your site

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/organizers/", text: "Organizers"}

topNavigationLinks:



# Organizers Block
teamBlockTitle: " "
aboutUs: "The festival team is composed ..."
