# Plugins
gems:

safe: false

# Build Settings
markdown: kramdown
permalink: pretty

# Site settings
title: Queer Festival of Colours
email: "addmail@mail.com"
description: Queer Festival of Colours at Cambridge,UK.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "/:title"
keywords: Queer, Festival, Cambridge
author: q+
url: "https://cihernand.github.io/queerfest" # the base hostname & protocol for your site

# Organizers Block
teamBlockTitle: " "
aboutUs: "The festival team is composed: The organising team consists of Claudia Hernandez (PhD student, Bioinformatics), Elmira Zadissa (MSc Politics, Creative Freelancer), Rosa Colaco (Museum Attendant) and Ramona Zadissa (MA Ethnology, Creative Freelancer)"
